# Generated by Django 6.1 on 2026-08-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100, verbose_name='宠物姓名')),
                ('pet_type', models.CharField(choices=[('dog', '狗狗'), ('cat', '猫咪'), ('other', '其他')], default='dog', max_length=20, verbose_name='宠物类型')),
                ('service', models.CharField(max_length=200, verbose_name='服务项目')),
                ('date', models.DateField(verbose_name='预约日期')),
                ('time', models.CharField(max_length=20, verbose_name='预约时段')),
                ('phone', models.CharField(max_length=20, verbose_name='主人手机号')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '预约记录',
                'verbose_name_plural': '预约记录',
                'db_table': 'contract',
                'ordering': ['-created_at'],
            },
        ),
    ]
