# Generated by Django 6.1 on 2026-08-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='breed',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='品种'),
        ),
        migrations.AddField(
            model_name='contract',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='体重(kg)'),
        ),
    ]
