"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&+o*b_pmnu8#08ne-j3%9mu^)@0zo=pc5yyqk0jl*0!p-60+q8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'dist',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# ============================================================
# 生产环境配置覆盖（部署到云端时通过环境变量激活）
# 本地开发保持默认：DEBUG=True + SQLite，无需改动
# ============================================================
import os

# 通过环境变量激活生产模式。Render/Vercel 等平台设置了本变量
IS_PRODUCTION = os.environ.get('DJANGO_PRODUCTION', '') == 'true'

if IS_PRODUCTION:
    DEBUG = os.environ.get('DJANGO_DEBUG', 'false').lower() == 'true'
    SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', SECRET_KEY)
    ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')

    # ---- 数据库：优先使用 DATABASE_URL（对应云端 PostgreSQL）----
    DATABASE_URL = os.environ.get('DATABASE_URL', '')
    if DATABASE_URL:
        import dj_database_url
        DATABASES['default'] = dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    else:
        # 无 DATABASE_URL 时回退到 SQLite，便于单机部署
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

    # ---- 安全 / 中间件 ----
    # 生产强制 HTTPS、安全 Cookie
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SSL_REDIRECT', 'true').lower() == 'true'
    SESSION_COOKIE_SECURE = os.environ.get('DJANGO_COOKIE_SECURE', 'true').lower() == 'true'
    CSRF_COOKIE_SECURE = os.environ.get('DJANGO_CSRF_COOKIE_SECURE', 'true').lower() == 'true'

    # ---- CORS：前端与后端域名不同，需允许跨域（对应知识库思路）----
    CORS_ALLOWED_ORIGINS = [
        o for o in os.environ.get(
            'DJANGO_CORS_ALLOWED_ORIGINS',
            'https://your-frontend.vercel.app',
        ).split(',') if o
    ]
    CORS_ALLOW_ALL_ORIGINS = os.environ.get('DJANGO_CORS_ALLOW_ALL', 'false').lower() == 'true'
    if 'corsheaders' not in INSTALLED_APPS:
        INSTALLED_APPS.insert(0, 'corsheaders')
    if 'corsheaders.middleware.CorsMiddleware' not in MIDDLEWARE:
        # 放最前，尽量靠前处理
        MIDDLEWARE = ['corsheaders.middleware.CorsMiddleware', *MIDDLEWARE]

    # ---- 静态文件：Whitenoise 托管（生产不需要单独静态服务器）----
    if 'whitenoise.middleware.WhiteNoiseMiddleware' not in MIDDLEWARE:
        MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')
    # 静态文件压缩存储（无 manifest 校验，避免部署失败）
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
